Delete redundant stress marks from 9 entries
gramdict/zalizniak-2010 pull request #8
Opened 2021-09-13 16:00 UTC by shenyileirob

10 hits for regex `(?<![аеиоуыэюя])́`.
- 9 entries corrected;
- 1 entry pending: **шё́лк-сыре́ц**.

2021-09-13 16:15 UTC, shenyileirob commented
Unfortunately I have only a scanned 1980 version at hand, and am unable to check if the first stress mark in **шё́лк-сыре́ц** is in the original text of the 2010 version. Would you help me with that?

2021-09-14 02:14 UTC, shenyileirob commented
A regex search outside `/dictionary/Нарицательные` found more hits.

34 hits for regex `(?<![аеиоуыэюя])́`:
- 32 corrected;
- 2 pending: **шё́лк-сыре́ц**, **Жи́ль Бл́аз**.

2021-09-14 05:57 UTC, bzaar commented
> Unfortunately I have only a scanned 1980 edition at hand, and am unable to check if the first stress mark in **шё́лк-сыре́ц** is in the original text of the 2010 edition. Would you help me with that?

I don't have the 2010 edition at hand either. Raised #9 so to remember to check later.

2021-09-14 06:08 UTC, bzaar requested changes
Would you mind fixing мещёра?

2021-09-14 06:08 UTC, bzaar commented on dictionary/Нарицательные/А.txt
> +мещера́ ж 1b— [//__меще́ра__ ж 1a] (_древнее племя, собир._)
I believe this should be a plain ё without a stress mark: https://w.wiki/44eY

2021-09-14 06:08 UTC, bzaar commented on dictionary/Нарицательные/Д.txt
> +род м 1c, П2(в) (_первобытная общественная организация; ряд поколений_) ✧ без ро́ду, без пле́мени; ни ро́ду, ни пле́мени; сто́лько-то ле́т о́т роду; э́то у него́ в роду́; на роду́ напи́сано; м 1e (_е
A rogue acute accent next to ✧ (just commenting).

2021-09-14 06:54 UTC, merged

2021-09-14 06:54 UTC, bzaar commented
Never mind, I'll fix мещёра myself.

2021-09-14 07:25 UTC, bzaar commented
> Never mind, I'll fix мещёра myself.

Done: https://github.com/gramdict/zalizniak-2010/commit/280e2505f793492bc1a7e177f0190ab58851b1d1

2021-09-14 07:27 UTC, bzaar commented
Thanks for your help!

2021-09-14 15:30 UTC, shenyileirob commented on dictionary/Нарицательные/А.txt
> +мещера́ ж 1b— [//__меще́ра__ ж 1a] (_древнее племя, собир._)
Are we trying to merely fix the digitization errors or to revise Zaliznjak (2010) in passing when appropriate?

2021-09-14 15:40 UTC, bzaar commented on dictionary/Нарицательные/А.txt
> +мещера́ ж 1b— [//__меще́ра__ ж 1a] (_древнее племя, собир._)
Good point. I think that we should keep these two goals separate. I suggest that in this repo we simply fix digitization errors. Any revisions and updates should go into a separate file/repo.

Raised #10.

2023-01-01 22:32 UTC, bzaar commented
> * 2 pending: **шё́лк-сыре́ц**, **Жи́ль Бл́аз**.

Sorry it took me a while a get around to checking this. Please see #9 for more details.